class KT1000Panel extends HTMLElement {
  constructor(){super();this.attachShadow({mode:"open"});this._hass=null;this.data=null;this.tab="overview";this.filter="all";this.accessPage=1;this.search="";this.tempPasswords=null;this.tempPasswordError=null;this.offlinePasswords=null;this.offlinePage=1;this.offlineFilter="all";this.showInvalidOffline=false;this.offlinePasswordError=null;this.passwordMode="online";this.showDeleted=false;this.peopleMode="local";this.selectedPerson=null;this.selectedLockUser=null;this.peopleSearch="";this.lockUsers=null;this.lockUsersError=null;}
  connectedCallback(){this.load();this._refreshTimer=setInterval(()=>{if(!this.shadowRoot.querySelector("dialog[open]"))this.load();},30000);}
  disconnectedCallback(){clearInterval(this._refreshTimer);}
  set hass(v){this._hass=v;if(!this.data)this.load();}
  set panel(v){this._panel=v;}
  async call(type,extra={}){const response=await fetch("./api/command",{method:"POST",headers:{"Content-Type":"application/json","X-KT1000-Request":"1"},body:JSON.stringify({type,...extra})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Falha na solicitação");return result;}
  async load(){try{this.data=await this.call("kt1000/overview");if(this.data.offline_sync_done||this.data.offline_items?.length){this.offlinePasswords=this.data.offline_items||[];this.offlinePasswordError=this.data.offline_sync_warning||null;}if(this.tab==="passwords"&&this.passwordMode==="online"){this.tempPasswords=null;this.tempPasswordError=null;}this.render();}catch(e){this.innerHTML="";this.shadowRoot.innerHTML=`<div style="padding:32px">Erro: ${this.escape(e.message||e)}</div>`}}
  fmt(ts){if(!ts)return "—";return new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(ts));}
  badge(code){return {"unlock_fingerprint":"Digital","unlock_card":"Tag","unlock_password":"Senha","unlock_temporary":"Temporária","unlock_app":"App"}[code]||code;}
  nav(id,label){return `<button class="nav ${this.tab===id?"active":""}" data-tab="${id}">${label}</button>`}
  render(){
    if(!this.data)return;
    const d=this.data,h=d.history||[],today=new Date().toDateString(),todayCount=h.filter(x=>new Date(x.event_time).toDateString()===today).length;
    const unknown=(d.credentials||[]).filter(x=>!x.person).length,last=h[0];
    this.shadowRoot.innerHTML=`<style>
      :host{display:block;background:var(--primary-background-color,#f5f7fb);color:var(--primary-text-color,#111827);min-height:100vh;font-family:Inter,system-ui,-apple-system,sans-serif}
      *{box-sizing:border-box}button:disabled{opacity:.45;cursor:default}.wrap{max-width:1440px;margin:auto;padding:28px}.top{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:24px}
      h1{font-size:26px;margin:0}.sub{color:var(--secondary-text-color,#6b7280);font-size:13px;margin-top:4px}.status{display:flex;align-items:center;gap:8px;font-size:13px}.dot{width:9px;height:9px;border-radius:50%;background:#16a34a}.dot.off{background:#dc2626}
      .tabs{display:flex;gap:4px;background:var(--card-background-color,#fff);padding:5px;border:1px solid var(--divider-color,#e5e7eb);border-radius:12px;width:max-content;margin-bottom:22px}.nav{border:0;background:transparent;padding:9px 14px;border-radius:9px;cursor:pointer;color:inherit}.nav.active{background:var(--primary-color,#2563eb);color:white}
      .cards{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:20px}.card,.panel{background:var(--card-background-color,#fff);border:1px solid var(--divider-color,#e5e7eb);border-radius:14px;box-shadow:0 1px 2px rgba(0,0,0,.03)}.card{padding:18px}.label{font-size:12px;color:var(--secondary-text-color,#6b7280);text-transform:uppercase;letter-spacing:.05em}.big{font-size:27px;font-weight:700;margin-top:8px}.panel{overflow:hidden}.panelhead{padding:17px 18px;border-bottom:1px solid var(--divider-color,#e5e7eb);display:flex;justify-content:space-between;align-items:center;gap:12px}.panelhead h2{font-size:16px;margin:0}
      table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:13px 18px;border-bottom:1px solid var(--divider-color,#eef0f3);font-size:13px}th{font-size:11px;text-transform:uppercase;color:var(--secondary-text-color,#6b7280);background:rgba(127,127,127,.035)}tr:last-child td{border-bottom:0}.badge{display:inline-block;padding:4px 8px;border-radius:999px;background:rgba(37,99,235,.1);font-size:11px;font-weight:600}.muted{color:var(--secondary-text-color,#6b7280)}.unknown{color:#d97706;font-weight:600}
      button.action{border:1px solid var(--divider-color,#d1d5db);background:var(--card-background-color,#fff);color:inherit;border-radius:8px;padding:7px 10px;cursor:pointer}.primary{background:var(--primary-color,#2563eb)!important;color:#fff!important;border-color:transparent!important}.danger{color:#dc2626!important}.toolbar{display:flex;gap:8px}.input,select{background:var(--card-background-color,#fff);color:inherit;border:1px solid var(--divider-color,#d1d5db);border-radius:9px;padding:8px 10px}
      .people{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.person{padding:18px}.person h3{margin:0 0 4px}.chips{display:flex;gap:6px;flex-wrap:wrap;margin:14px 0}.empty{padding:34px;text-align:center;color:var(--secondary-text-color,#6b7280)}
      dialog{border:0;border-radius:16px;padding:0;background:var(--card-background-color,#fff);color:inherit;box-shadow:0 24px 80px rgba(0,0,0,.25);min-width:360px}dialog::backdrop{background:rgba(0,0,0,.42)}.modal{padding:22px}.modal h3{margin-top:0}.modalrow{display:flex;gap:8px;justify-content:flex-end;margin-top:18px}
      @media(max-width:900px){.cards{grid-template-columns:repeat(2,1fr)}.people{grid-template-columns:1fr}.wrap{padding:16px}.tablewrap{overflow:auto}}@media(max-width:520px){.cards{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}.tabs{width:100%;overflow:auto}.toolbar{flex-wrap:wrap}.panelhead{align-items:flex-start;flex-wrap:wrap}dialog{min-width:0;width:calc(100vw - 32px)}}
    </style><div class="wrap">
      <div class="top"><div style="display:flex;align-items:center;gap:12px"><img src="./assets/icon-64.png" style="width:46px;height:46px;border-radius:10px"><div><h1>KT-1000</h1><div class="sub">${this.escape(d.title)} · Controle de acesso · v0.12.0</div></div></div><div style="display:flex;align-items:center;gap:12px"><button class="action primary" id="remoteUnlock" ${d.remote_unlock_enabled?"":"disabled"} title="Habilite nas opções somente quando puder verificar a porta">🔓 Desbloquear</button><div class="status"><span class="dot ${d.online?"":"off"}"></span>${d.communication_pending?"Conectando à Tuya Cloud…":(d.online?"Tuya Cloud online":"Falha na comunicação")} · bateria ${d.battery??"—"}%${d.mqtt_enabled ? " · MQTT "+(d.mqtt_connected ? "conectado" : "aguardando conexão") : ""}</div></div></div>
      <div class="tabs"><button class="nav" id="importData">Importar dados</button>${this.nav("overview","Visão geral")}${this.nav("access","Acessos")}${this.nav("people","Pessoas")}${this.nav("passwords","Senhas temporárias")}</div>
      <div class="toolbar" style="margin-bottom:16px"><button class="action" id="refreshConnection">Atualizar conexão</button></div>
      ${d.communication_error?`<div class="panel" style="padding:16px;margin-bottom:18px"><strong class="unknown">Falha na comunicação com a Tuya</strong><div style="margin-top:8px">${this.escape(d.communication_error)}</div><div class="muted" style="margin-top:8px">O histórico salvo e as pessoas continuam disponíveis. A importação não transfere as credenciais Tuya para as opções do App.</div></div>`:""}
      <main>${this.content(todayCount,unknown,last)}</main>
      <dialog id="dlg"><div class="modal" id="modal"></div></dialog>
    </div>`;
    this.bind();
  }
  content(todayCount,unknown,last){
    if(this.tab==="overview")return `<div class="cards"><div class="card"><div class="label">Acessos hoje</div><div class="big">${todayCount}</div></div><div class="card"><div class="label">Bateria</div><div class="big">${this.data.battery??"—"}%</div></div><div class="card"><div class="label">Credenciais</div><div class="big">${this.data.credentials.length}</div></div><div class="card"><div class="label">Não identificadas</div><div class="big">${unknown}</div></div></div>${last?`<div class="panel"><div class="panelhead"><h2>Último acesso</h2></div><div class="card"><div class="big" style="font-size:20px">${this.escape(last.person||"Não identificado")}</div><div class="muted">${this.escape(last.method)} · #${this.escape(last.credential_id)} · ${this.fmt(last.event_time)}</div></div></div>`:""}`;
    if(this.tab==="access")return this.accessTable();
    if(this.tab==="people")return this.peopleHub();
    if(this.tab==="credentials")return this.credentialsView();
    return this.passwordsView();
  }
  accessTable(){
    let rows=this.data.history.filter(x=>this.filter==="all"||x.code===this.filter).filter(x=>!this.search||((x.person||"não identificado")+" "+x.credential_id).toLowerCase().includes(this.search.toLowerCase()));
    const total=rows.length,pages=Math.max(1,Math.ceil(total/20));this.accessPage=Math.min(Math.max(1,this.accessPage),pages);rows=rows.slice((this.accessPage-1)*20,this.accessPage*20);
    return `<div class="panel"><div class="panelhead"><h2>Histórico de acessos</h2><div class="toolbar"><input class="input" id="search" placeholder="Buscar pessoa ou ID" value="${this.escape(this.search)}"><select id="filter"><option value="all">Todos os métodos</option><option value="unlock_fingerprint">Digitais</option><option value="unlock_card">Tags</option><option value="unlock_password">Senhas</option><option value="unlock_temporary">Temporárias</option><option value="unlock_app">Aplicativo</option></select></div></div><div class="tablewrap"><table><thead><tr><th>Horário</th><th>Pessoa</th><th>Método</th><th>Credencial</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td>${this.fmt(x.event_time)}</td><td class="${x.person?"":"unknown"}">${this.escape(x.person||"Não identificado")}</td><td><span class="badge">${this.escape(this.badge(x.code))}</span></td><td>#${this.escape(x.credential_id)}</td><td>${x.person?"":`<button class="action assign" data-cred="${x.code}:${this.escape(x.credential_id)}">Associar</button>`}</td></tr>`).join("")}</tbody></table></div><div class="panelhead"><span>${total} registros · Página ${this.accessPage} de ${pages} · 20 por página</span><div class="toolbar"><button class="action" id="prevAccess" ${this.accessPage===1?"disabled":""}>Anterior</button><button class="action" id="nextAccess" ${this.accessPage===pages?"disabled":""}>Próxima</button></div></div></div>`;
  }
  credentialLabel(key){const [code,...id]=key.split(":");return `${this.badge(code)} #${id.join(":")}`;}
  availableCredentials(){const assigned=new Set(this.data.people.flatMap(p=>p.credentials||[]));return (this.data.credentials||[]).filter(c=>!assigned.has(c.key));}
  peopleHub(){
    const nav=`<div class="tabs"><button class="action ${this.peopleMode==="local"?"primary":""}" id="localPeople">Pessoas e acessos</button><button class="action ${this.peopleMode==="lock"?"primary":""}" id="lockPeople">Usuários da fechadura</button></div>`;
    return nav+(this.peopleMode==="local"?this.peopleView():this.credentialsView());
  }
  peopleView(){
    if(this.selectedPerson){const person=this.data.people.find(p=>p.name===this.selectedPerson);if(person)return this.personDetail(person);this.selectedPerson=null;}
    const people=this.data.people.filter(p=>!this.peopleSearch||p.name.toLowerCase().includes(this.peopleSearch.toLowerCase()));
    const available=this.availableCredentials().length;
    return `<div class="panelhead" style="padding:0 0 14px;border:0"><div><h2>Pessoas</h2><div class="muted">Entre em uma pessoa para administrar suas associações · ${available} credenciais disponíveis</div></div><div class="toolbar"><input class="input" id="peopleSearch" placeholder="Buscar pessoa" value="${this.escape(this.peopleSearch)}"><button class="action primary" id="newPerson">+ Nova pessoa</button></div></div><div class="people">${people.length?people.map(p=>`<div class="card person"><h3>${this.escape(p.name)}</h3><div class="muted">${p.credentials.length} credencial(is) associada(s)</div><div class="chips">${p.credentials.slice(0,4).map(c=>`<span class="badge">${this.escape(this.credentialLabel(c))}</span>`).join("")}${p.credentials.length>4?`<span class="badge">+${p.credentials.length-4}</span>`:""}</div><button class="action primary openPerson" data-name="${this.escape(p.name)}">Gerenciar credenciais</button></div>`).join(""):`<div class="panel empty">${this.peopleSearch?"Nenhuma pessoa encontrada.":"Crie uma pessoa para começar a associar credenciais."}</div>`}</div><div class="muted" style="margin-top:16px">Estas associações identificam os acessos no App. Para cadastrar ou excluir uma credencial na fechadura, abra Usuários da fechadura.</div>`;
  }
  personDetail(p){
    const available=this.availableCredentials();
    return `<div class="panel"><div class="panelhead"><div><button class="action" id="backPeople">← Pessoas</button><h2 style="margin-top:12px">${this.escape(p.name)}</h2><div class="muted">${p.credentials.length} credencial(is) · identificação dos acessos</div></div><div class="toolbar"><button class="action editPerson" data-name="${this.escape(p.name)}">Editar nome</button><button class="action primary" id="addPersonCredential" ${available.length?"":"disabled"}>+ Adicionar credencial (${available.length})</button></div></div><div class="tablewrap"><table><thead><tr><th>Credencial</th><th>Último uso</th><th>Ações</th></tr></thead><tbody>${p.credentials.length?p.credentials.map(key=>{const c=this.data.credentials.find(x=>x.key===key);return `<tr><td><span class="badge">${this.escape(this.credentialLabel(key))}</span></td><td>${c?.last_used?this.fmt(c.last_used):"Sem acesso registrado"}</td><td><div class="toolbar"><button class="action transferPersonCredential" data-cred="${this.escape(key)}" data-person="${this.escape(p.name)}" ${this.data.people.length>1?"":"disabled"}>Transferir</button><button class="action danger removePersonCredential" data-cred="${this.escape(key)}" data-person="${this.escape(p.name)}">Desassociar</button></div></td></tr>`}).join(""):`<tr><td colspan="3" class="empty">Nenhuma credencial associada. Use Adicionar credencial para escolher uma disponível.</td></tr>`}</tbody></table></div><div class="panelhead muted">Adicionar, desassociar e transferir alteram a identificação no App, inclusive o nome exibido no histórico. Não removem o acesso físico da fechadura.</div><div class="panelhead"><button class="action danger deletePerson" data-name="${this.escape(p.name)}">Excluir pessoa do App</button></div></div>`;
  }
  credentialsView(){
    if(this.lockUsers===null&&!this.lockUsersError){setTimeout(()=>this.loadLockUsers(),0);return `<div class="panel empty">Consultando usuários da fechadura…</div>`;}
    const users=this.lockUsers||[],selected=users.find(u=>String(u.user_id)===String(this.selectedLockUser));
    if(selected)return `<div class="panel"><div class="panelhead"><div><button class="action" id="backLockPeople">← Usuários da fechadura</button><h2 style="margin-top:12px">${this.escape(selected.nick_name||selected.user_id)}</h2><div class="muted">Cadastro sincronizado com a Tuya · operações na fechadura</div></div><button class="action" id="refreshLockUsers">Atualizar</button></div><div class="tablewrap"><table><thead><tr><th>Usuário</th><th>Tipo</th><th>Credencial</th><th>ID/SN</th><th>Ações</th></tr></thead><tbody>${this.userCredentialRows(selected).join("")}</tbody></table></div><div class="panelhead muted">Excluir da fechadura solicita a remoção física da credencial pela Tuya. Cadastrar senha, digital ou tag exige concluir a captura no local. Isso é diferente de desassociar uma pessoa no histórico.</div></div>`;
    this.selectedLockUser=null;
    return `<div class="panelhead" style="padding:0 0 14px;border:0"><div><h2>Usuários da fechadura</h2><div class="muted">Abra um usuário para gerenciar suas senhas, digitais e tags.</div></div><div class="toolbar"><button class="action primary" id="newLockUser">+ Novo usuário</button><button class="action" id="refreshLockUsers">Atualizar</button></div></div>${this.lockUsersError?`<div class="panel empty unknown">${this.escape(this.lockUsersError)}</div>`:`<div class="people">${users.length?users.map(u=>{const count=(u.unlock_detail||[]).reduce((n,d)=>n+(d.unlock_list||[]).length,0);return `<div class="card person"><h3>${this.escape(u.nick_name||u.user_id)}</h3><div class="muted">${count} credencial(is) na fechadura</div><div class="chips">${(u.unlock_detail||[]).map(d=>`<span class="badge">${this.escape(this.badge(d.dp_code))} · ${(d.unlock_list||[]).length}</span>`).join("")}</div><button class="action primary openLockPerson" data-user="${this.escape(u.user_id)}">Gerenciar credenciais</button></div>`}).join(""):`<div class="panel empty">Nenhum usuário retornado pela Tuya.</div>`}</div>`}`;
  }
  addPersonCredentialModal(person){
    const available=this.availableCredentials(),dlg=this.shadowRoot.querySelector("#dlg"),m=this.shadowRoot.querySelector("#modal");
    m.innerHTML=`<h3>Adicionar credencial a ${this.escape(person)}</h3><div class="muted">Somente credenciais sem associação no App estão disponíveis.</div><select id="availableCredential" style="width:100%;margin-top:16px">${available.map(c=>`<option value="${this.escape(c.key)}">${this.escape(this.credentialLabel(c.key))}${c.last_used?" · "+this.fmt(c.last_used):""}</option>`).join("")}</select><div class="modalrow"><button class="action" id="cancel">Cancelar</button><button class="action primary" id="save" ${available.length?"":"disabled"}>Adicionar</button></div><div class="unknown" id="personMessage"></div>`;
    dlg.showModal();m.querySelector("#cancel").onclick=()=>dlg.close();m.querySelector("#save").onclick=async()=>{const button=m.querySelector("#save");button.disabled=true;try{const credential=m.querySelector("#availableCredential").value;await this.call("kt1000/assign",{entry_id:this.data.entry_id,person,credential});dlg.close();await this.load();}catch(e){m.querySelector("#personMessage").textContent=e.message||e;button.disabled=false;}};
  }
  transferPersonCredentialModal(credential,source){
    const destinations=this.data.people.filter(p=>p.name!==source),dlg=this.shadowRoot.querySelector("#dlg"),m=this.shadowRoot.querySelector("#modal");
    m.innerHTML=`<h3>Transferir credencial</h3><p>${this.escape(this.credentialLabel(credential))} · atualmente em ${this.escape(source)}</p><label>Nova pessoa</label><select id="destination" style="width:100%;margin-top:8px">${destinations.map(p=>`<option value="${this.escape(p.name)}">${this.escape(p.name)}</option>`).join("")}</select><p class="muted">O nome nos registros de acesso passará a ser o da nova pessoa. Esta ação não altera o cadastro na fechadura.</p><div class="modalrow"><button class="action" id="cancel">Cancelar</button><button class="action primary" id="save">Transferir</button></div><div class="unknown" id="personMessage"></div>`;
    dlg.showModal();m.querySelector("#cancel").onclick=()=>dlg.close();m.querySelector("#save").onclick=async()=>{const button=m.querySelector("#save");button.disabled=true;try{await this.call("kt1000/assign",{entry_id:this.data.entry_id,person:m.querySelector("#destination").value,credential,expected_owner:source});dlg.close();await this.load();}catch(e){m.querySelector("#personMessage").textContent=e.message||e;button.disabled=false;}};
  }
  async removePersonCredential(credential,person){if(!confirm(`Desassociar ${this.credentialLabel(credential)} de ${person}?\n\nEla ficará disponível para outra pessoa no App. O acesso físico à fechadura permanece.`))return;try{await this.call("kt1000/unassign",{entry_id:this.data.entry_id,credential,expected_person:person});await this.load();}catch(e){alert(e.message||e);}}
  userCredentialRows(u){const details=u.unlock_detail||[];const list=[];const uid=this.escape(u.user_id);const utype=Number(u.user_type||20);const role=utype===50?"Proprietário":utype===10?"Administrador":"Usuário";for(const d of details){for(const k of (d.unlock_list||[])){list.push(`<tr><td><b>${this.escape(u.nick_name||u.user_id||"—")}</b><div class="muted">${role}</div></td><td><span class="badge">${this.badge(d.dp_code)}</span></td><td>${this.escape(k.unlock_name||"—")}</td><td>#${this.escape(k.unlock_sn??k.unlock_id??"—")}</td><td><div class="toolbar">${d.dp_code==="unlock_password"?`<button class="action primary changeFixedPassword" data-user="${uid}" data-sn="${this.escape(k.unlock_sn)}">Trocar senha</button>`:""}<button class="action renameOpmode" data-sn="${this.escape(k.unlock_sn)}" data-name="${this.escape(k.unlock_name||"")}">Renomear</button><button class="action danger deleteUnlock" data-user="${uid}" data-type="${this.escape((d.dp_code||"").replace("unlock_",""))}" data-no="${this.escape(k.unlock_sn)}" data-utype="2">Excluir da fechadura</button></div></td></tr>`);}}list.push(`<tr><td>${this.escape(u.nick_name||u.user_id||"—")}</td><td colspan="3"><div class="toolbar"><button class="action addCredential" data-user="${uid}" data-kind="password">Cadastrar senha</button><button class="action addCredential" data-user="${uid}" data-kind="fingerprint">Cadastrar digital</button><button class="action addCredential" data-user="${uid}" data-kind="card">Cadastrar tag/cartão</button>${utype!==50?`<button class="action setRole" data-user="${uid}" data-role="${utype===10?'normal':'admin'}">${utype===10?'Tornar usuário':'Tornar administrador'}</button>`:''}<button class="action editLockUser" data-user="${uid}" data-name="${this.escape(u.nick_name||'')}">Editar usuário</button><button class="action danger deleteLockUser" data-user="${uid}" data-name="${this.escape(u.nick_name||u.user_id||'usuário')}">Excluir usuário</button></div></td><td></td></tr>`);return list;}

  phaseLabel(v){
    const map={0:"Excluída",1:"Aguardando envio",2:"Ativa",3:"Congelada",4:"Excluída",5:"Falha"};
    return map[v] ?? (v===null||v===undefined?"—":String(v));
  }
  passwordStatus(x){
    const phase=Number(x.phase),now=Date.now()/1000,start=Number(x.effective_time||0),end=Number(x.invalid_time||0);
    if([0,4].includes(phase))return "Excluída";
    if(end && end<now)return "Vencida";
    if(start && start>now)return "Agendada";
    if(phase===3)return "Congelada";
    return this.phaseLabel(x.phase);
  }
  unixFmt(v){
    if(!v)return "—";
    const n=Number(v); const ms=n<1000000000000?n*1000:n;
    return new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(ms));
  }
  passwordsView(){
    const offline=this.passwordMode==="offline";
    if(offline)return this.offlineView();
    if(!offline && this.tempPasswords===null && !this.tempPasswordError){setTimeout(()=>this.loadTempPasswords(),0);return `<div class="panel empty">Consultando senhas online na Tuya Cloud…</div>`;}
    const all=this.tempPasswords||[],rows=this.showDeleted?all:all.filter(x=>![0,4,"0","4"].includes(x.phase));
    return `<div class="panel">
      <div class="panelhead"><div><h2>Senhas temporárias</h2><div class="muted" style="margin-top:4px">${offline?"Offline · funcionam mesmo sem Wi-Fi na fechadura":"Online · sincronizadas pela Tuya Cloud"}</div></div>
      <div class="toolbar">${!offline?'<button class="action" id="refreshPasswords">Atualizar</button>':''}<button class="action primary" id="createPassword">+ Criar senha</button></div></div>
      <div style="padding:12px 18px;border-bottom:1px solid var(--divider-color,#e5e7eb);display:flex;gap:8px;align-items:center;flex-wrap:wrap">
        <button class="action ${offline?'':'primary'}" id="modeOnline">Online</button><button class="action ${offline?'primary':''}" id="modeOffline">Offline</button>
        ${!offline?`<label class="muted" style="margin-left:auto;display:flex;gap:7px;align-items:center"><input type="checkbox" id="showDeleted" ${this.showDeleted?'checked':''}> Mostrar excluídas (${all.length-rows.length})</label>`:''}
      </div>
      ${(this.tempPasswordError?`<div class="empty"><div class="unknown">A API não retornou a lista.</div><div class="muted" style="margin-top:8px">${this.escape(this.tempPasswordError)}</div></div>`:
      `<div class="tablewrap"><table><thead><tr><th>Nome</th><th>ID</th><th>Status</th><th>Início</th><th>Fim</th><th>Tipo</th><th></th></tr></thead><tbody>
      ${rows.length?rows.map(x=>{const id=x.id??x.password_id??"",status=this.passwordStatus(x),expired=status==="Vencida",frozen=Number(x.phase)===3;const typ=Number(x.type)===1?"Uso único":"Por período";return `<tr><td>${this.escape(x.name||"Sem nome")}</td><td>#${this.escape(id||"—")}</td><td><span class="badge">${status}</span></td><td>${this.unixFmt(x.effective_time)}</td><td>${this.unixFmt(x.invalid_time)}</td><td>${typ}</td><td><div class="toolbar"><button class="action pwdDetail" data-id="${this.escape(id)}">Detalhes</button>${frozen&&!expired?`<button class="action primary pwdUnfreeze" data-id="${this.escape(id)}">Reativar</button>`:(!frozen&&!expired&&status==="Ativa"?`<button class="action pwdFreeze" data-id="${this.escape(id)}">Congelar</button>`:'')}<button class="action danger ${expired||status==="Excluída"?"pwdDeleteRecord":"pwdDelete"}" data-id="${this.escape(id)}" data-name="${this.escape(x.name||'Senha temporária')}">${expired||status==="Excluída"?"Excluir registro":"Excluir"}</button></div></td></tr>`}).join(""):`<tr><td colspan="7" class="empty">Nenhuma senha online encontrada.</td></tr>`}</tbody></table></div>`)}
      <div style="padding:14px 18px;border-top:1px solid var(--divider-color,#e5e7eb)" class="muted">${offline?"As senhas offline são calculadas pela Tuya e o código é exibido somente no momento da geração.":"Senhas vencidas usam Excluir registro, que remove o histórico na Tuya. Senhas ativas usam Excluir para solicitar a remoção da senha. Nenhuma dessas ações estende a validade."}</div>
    </div>`;
  }
  offlineStatus(x){
    if(Number(x.status)===2)return "Utilizada";
    if(Number(x.status)===3)return "Inválida";
    if(x.invalid_time&&Number(x.invalid_time)<=Date.now()/1000)return "Vencida";
    if(x.effective_time&&Number(x.effective_time)>Date.now()/1000)return "Agendada";
    if(x.cloud_present===false)return "Não confirmada pela Tuya";
    return Number(x.status)===1?"Disponível":"Gerada";
  }
  offlineView(){
    if(this.offlinePasswords===null){setTimeout(()=>this.loadOfflinePasswords(),0);return `<div class="panel empty">Carregando histórico offline…</div>`;}
    const invalid=x=>["Utilizada","Inválida","Vencida"].includes(this.offlineStatus(x));
    let rows=(this.offlinePasswords||[]).filter(x=>this.offlineFilter==="all"||x.type===this.offlineFilter).filter(x=>this.showInvalidOffline||!invalid(x));
    const total=rows.length,pages=Math.max(1,Math.ceil(total/20));this.offlinePage=Math.min(Math.max(1,this.offlinePage),pages);rows=rows.slice((this.offlinePage-1)*20,this.offlinePage*20);
    const types={once:"Uso único",multiple:"Por período",clear_one:"Limpeza individual",clear_all:"Limpeza geral"};
    return `<div class="panel"><div class="panelhead"><div><h2>Senhas temporárias offline</h2><div class="muted">Histórico persistente · sincronização Tuya periódica${this.data.offline_last_sync?" · "+this.fmt(Date.parse(this.data.offline_last_sync)):""}</div></div><div class="toolbar"><button class="action" id="refreshPasswords">Atualizar</button><button class="action primary" id="createPassword">+ Criar senha</button></div></div><div class="panelhead"><div class="toolbar"><button class="action" id="modeOnline">Online</button><button class="action primary" id="modeOffline">Offline</button><select id="offlineFilter"><option value="all">Todos os tipos</option><option value="once">Uso único</option><option value="multiple">Por período</option><option value="clear_one">Limpeza individual</option><option value="clear_all">Limpeza geral</option></select></div><label><input type="checkbox" id="showInvalidOffline" ${this.showInvalidOffline?"checked":""}> Mostrar utilizadas e inválidas</label></div>
    ${this.offlinePasswordError?`<div class="panelhead unknown">${this.escape(this.offlinePasswordError)}</div>`:""}<div class="tablewrap"><table><thead><tr><th>Nome</th><th>ID</th><th>Tipo</th><th>Status</th><th>Início</th><th>Fim</th><th></th></tr></thead><tbody>${rows.length?rows.map(x=>`<tr><td>${this.escape(x.name||"Sem nome")}${x.cloud_present===false?'<div class="muted">Somente histórico local · não retornada pela Tuya</div>':""}</td><td>${this.escape(x.id)}</td><td>${this.escape(types[x.type]||x.type)}</td><td><span class="badge">${this.offlineStatus(x)}</span></td><td>${this.unixFmt(x.effective_time)}</td><td>${this.unixFmt(x.invalid_time)}</td><td>${x.has_code?`<button class="action offlineCode" data-id="${this.escape(x.id)}">Ver código</button>`:`<span class="muted">Código não disponível</span>`}</td></tr>`).join(""):`<tr><td colspan="7" class="empty">Nenhuma senha neste filtro. Atualize para consultar a Tuya ou crie uma senha pelo App.</td></tr>`}</tbody></table></div><div class="panelhead"><span>${total} registros · Página ${this.offlinePage} de ${pages} · 20 por página</span><div class="toolbar"><button class="action" id="prevOffline" ${this.offlinePage===1?"disabled":""}>Anterior</button><button class="action" id="nextOffline" ${this.offlinePage===pages?"disabled":""}>Próxima</button></div></div><div class="panelhead muted">O código das novas senhas deste App fica salvo de forma criptografada. A sincronização não recupera códigos antigos. “Gerada” não confirma se a senha já foi utilizada; os estados da Tuya aparecem após sincronizar. Códigos de limpeza exigem digitação na fechadura.</div></div>`;
  }
  async revealOfflineCode(id){
    const dlg=this.shadowRoot.querySelector("#dlg"),m=this.shadowRoot.querySelector("#modal");m.innerHTML=`<h3>Código offline</h3><p>Consultando…</p>`;dlg.showModal();
    try{const r=await this.call("kt1000/offline_password_code",{entry_id:this.data.entry_id,password_id:id});const row=(this.offlinePasswords||[]).find(x=>x.id===id)||{};m.innerHTML=`<h3>${this.escape(row.name||"Senha offline")}</h3><div style="font-size:30px;text-align:center;padding:24px">${this.escape(r.code)}</div><div class="muted">Validade: ${this.unixFmt(row.invalid_time)}. Consultar o código não envia comandos à fechadura.</div><div class="modalrow"><button class="action" id="closeCode">Fechar</button></div>`;}catch(e){m.innerHTML=`<h3>Não foi possível consultar</h3><p>${this.escape(e.message||e)}</p><button class="action" id="closeCode">Fechar</button>`;}
    m.querySelector("#closeCode").onclick=()=>{m.innerHTML="";dlg.close();};
  }
  escape(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
  async loadTempPasswords(){
    try{
      const r=await this.call("kt1000/temp_passwords",{entry_id:this.data.entry_id});
      if(!r.ok){this.tempPasswordError=r.error||"Erro desconhecido";this.tempPasswords=[];}
      else{this.tempPasswordError=null;this.tempPasswords=r.items||[];}
    }catch(e){this.tempPasswordError=e.message||String(e);this.tempPasswords=[];}
    this.render();
  }
  async loadOfflinePasswords(){
    try{const r=await this.call("kt1000/offline_temp_passwords",{entry_id:this.data.entry_id});if(!r.ok){this.offlinePasswordError=r.error||"Erro desconhecido";this.offlinePasswords=[];}else{this.offlinePasswordError=r.warning||null;this.offlinePasswords=r.items||[];}}
    catch(e){this.offlinePasswordError=e.message||String(e);this.offlinePasswords=[];}this.render();
  }
  async passwordDetail(id){
    const dlg=this.shadowRoot.querySelector("#dlg"),m=this.shadowRoot.querySelector("#modal");
    m.innerHTML=`<h3>Detalhes da senha</h3><div class="muted">Consultando #${this.escape(id)}…</div>`;dlg.showModal();
    try{
      const r=await this.call("kt1000/temp_password_detail",{entry_id:this.data.entry_id,password_id:id});
      if(!r.ok)throw new Error(r.error||"Falha na consulta");
      const x=r.item||{};
      m.innerHTML=`<h3>${this.escape(x.name||"Senha temporária")}</h3>
        <table><tbody>
        <tr><td class="muted">ID</td><td>#${this.escape(x.id??id)}</td></tr>
        <tr><td class="muted">Status</td><td>${this.passwordStatus(x)}</td></tr>
        <tr><td class="muted">Início</td><td>${this.unixFmt(x.effective_time)}</td></tr>
        <tr><td class="muted">Fim</td><td>${this.unixFmt(x.invalid_time)}</td></tr>
        <tr><td class="muted">Entrega</td><td>${this.escape(x.delivery_status??"—")}</td></tr>
        <tr><td class="muted">Fuso</td><td>${this.escape(x.time_zone??"—")}</td></tr>
        <tr><td class="muted">Tipo</td><td>${this.escape(x.type??x.password_type??"—")}</td></tr>
        </tbody></table><div class="modalrow"><button class="action primary" id="closePwd">Fechar</button></div>`;
      m.querySelector("#closePwd").onclick=()=>dlg.close();
    }catch(e){m.innerHTML=`<h3>Falha na consulta</h3><div class="unknown">${this.escape(e.message||e)}</div><div class="modalrow"><button class="action" id="closePwd">Fechar</button></div>`;m.querySelector("#closePwd").onclick=()=>dlg.close();}
  }
  localInputValue(d){
    const pad=n=>String(n).padStart(2,"0");
    return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
  }
  createPasswordModal(){
    if(this.passwordMode==="offline")return this.createOfflinePasswordModal();
    const dlg=this.shadowRoot.querySelector("#dlg"),m=this.shadowRoot.querySelector("#modal");const now=new Date(),end=new Date(now.getTime()+24*60*60*1000);
    m.innerHTML=`<h3>Criar senha online por período</h3><div class="muted" style="margin-bottom:14px">A senha é enviada à fechadura pela Tuya Cloud.</div><label>Nome</label><input class="input" id="pwdName" style="width:100%;margin:6px 0 12px"><label>Senha</label><input class="input" id="pwdValue" type="password" inputmode="numeric" maxlength="7" placeholder="7 dígitos" style="width:100%;margin:6px 0 12px"><label>Início</label><input class="input" id="pwdStart" type="datetime-local" value="${this.localInputValue(now)}" style="width:100%;margin:6px 0 12px"><label>Fim</label><input class="input" id="pwdEnd" type="datetime-local" value="${this.localInputValue(end)}" style="width:100%;margin:6px 0 12px"><div id="pwdMsg" class="unknown" style="margin-top:12px"></div><div class="modalrow"><button class="action" id="cancelPwd">Cancelar</button><button class="action primary" id="savePwd">Criar senha</button></div>`;dlg.showModal();m.querySelector("#cancelPwd").onclick=()=>dlg.close();m.querySelector("#savePwd").onclick=async()=>{const name=m.querySelector("#pwdName").value.trim(),password=m.querySelector("#pwdValue").value.trim(),st=new Date(m.querySelector("#pwdStart").value),en=new Date(m.querySelector("#pwdEnd").value),msg=m.querySelector("#pwdMsg");if(!name)return msg.textContent="Informe um nome.";if(!/^\d{7}$/.test(password))return msg.textContent="A senha deve ter exatamente 7 dígitos.";if(en<=st)return msg.textContent="Confira o período.";try{const r=await this.call("kt1000/create_temp_password",{entry_id:this.data.entry_id,name,password,effective_time:Math.floor(st/1000),invalid_time:Math.floor(en/1000),use_once:false});m.querySelector("#pwdValue").value="";if(!r.ok)throw new Error(r.error);dlg.close();this.tempPasswords=null;this.render();}catch(e){msg.textContent=e.message||e;}};
  }
  createOfflinePasswordModal(){
    const dlg=this.shadowRoot.querySelector("#dlg"),m=this.shadowRoot.querySelector("#modal"),now=new Date(),end=new Date(now.getTime()+24*60*60*1000);
    m.innerHTML=`<h3>Gerar senha offline</h3><label>Tipo</label><select id="offType" style="width:100%;margin:6px 0 12px"><option value="1">Uso único</option><option value="0">Por período</option><option value="9">Código para apagar todas</option></select><div id="offFields"><label>Nome</label><input class="input" id="offName" placeholder="Ex.: Prestador" style="width:100%;margin:6px 0 12px"><div id="periodFields"><label>Início</label><input class="input" id="offStart" type="datetime-local" value="${this.localInputValue(now)}" style="width:100%;margin:6px 0 12px"><label>Fim</label><input class="input" id="offEnd" type="datetime-local" value="${this.localInputValue(end)}" style="width:100%;margin:6px 0 12px"></div></div><div id="pwdMsg" class="unknown" style="margin-top:12px"></div><div class="modalrow"><button class="action" id="cancelPwd">Cancelar</button><button class="action primary" id="savePwd">Gerar</button></div>`;dlg.showModal();const typ=m.querySelector("#offType");const sync=()=>{m.querySelector("#periodFields").style.display=typ.value==="0"?"block":"none";m.querySelector("#offFields").style.display=typ.value==="9"?"none":"block"};typ.onchange=sync;sync();m.querySelector("#cancelPwd").onclick=()=>dlg.close();m.querySelector("#savePwd").onclick=async()=>{const t=Number(typ.value),msg=m.querySelector("#pwdMsg"),payload={entry_id:this.data.entry_id,pwd_type:t,name:m.querySelector("#offName")?.value.trim()||""};if(t===0){const st=new Date(m.querySelector("#offStart").value),en=new Date(m.querySelector("#offEnd").value);if(en<=st)return msg.textContent="Confira o período.";payload.effective_time=Math.floor(st/1000);payload.invalid_time=Math.floor(en/1000);}else{payload.effective_time=Math.floor(Date.now()/3600000)*3600;}try{const r=await this.call("kt1000/create_offline_temp_password",payload);if(!r.ok)throw new Error(r.error);this.showOfflineSecret(r.result,t,r.warning);this.offlinePasswords=null;}catch(e){msg.textContent=e.message||e;}};
  }
  showOfflineSecret(result,type,warning=null){const m=this.shadowRoot.querySelector("#modal");const code=result?.offline_temp_password||result?.password||result?.pwd||"—";m.innerHTML=`<h3>${type===9?'Código para apagar todas as senhas offline':'Senha offline gerada'}</h3><div class="muted">${warning?this.escape(warning):"Código salvo de forma criptografada. Ele poderá ser consultado novamente na lista offline."}</div><div style="font-size:30px;font-weight:700;letter-spacing:3px;text-align:center;padding:24px">${this.escape(code)}</div>${type===9?'<div class="unknown">Digite este código na fechadura para efetivar a limpeza das senhas offline.</div>':''}<div class="modalrow"><button class="action primary" id="closeSecret">Fechar</button></div>`;m.querySelector("#closeSecret").onclick=()=>{m.innerHTML="";this.shadowRoot.querySelector("#dlg").close();this.offlinePasswords=null;this.render();};}
  async clearOfflineOne(id){if(!confirm("Gerar código para apagar esta senha offline? O código deverá ser digitado na fechadura."))return;try{const r=await this.call("kt1000/create_offline_temp_password",{entry_id:this.data.entry_id,pwd_type:8,password_id:id});if(!r.ok)throw new Error(r.error);const dlg=this.shadowRoot.querySelector("#dlg");dlg.showModal();this.showOfflineSecret(r.result,8);}catch(e){alert(e.message||e);}}
  async setPasswordFrozen(id,frozen){
    const verb=frozen?"congelar":"reativar";
    if(!confirm(`Deseja ${verb} a senha #${id}?`))return;
    try{const r=await this.call("kt1000/set_temp_password_frozen",{entry_id:this.data.entry_id,password_id:id,frozen});if(!r.ok)throw new Error(r.error||`Falha ao ${verb}`);this.tempPasswords=null;this.tempPasswordError=null;this.render();}
    catch(e){alert(e.message||e);}
  }
  async deletePasswordRecord(id,name){
    if(!confirm(`Excluir o registro histórico de "${name}" (#${id}) na Tuya?\n\nEsta ação remove o histórico de uma senha vencida/excluída. Ela não reativa a senha nem abre a porta.`))return;
    try{const r=await this.call("kt1000/delete_temp_password_record",{entry_id:this.data.entry_id,password_id:id});if(!r.ok)throw new Error(r.error||"Falha ao excluir registro");this.tempPasswords=null;this.tempPasswordError=null;this.render();}catch(e){alert(e.message||e);}
  }
  async deletePassword(id,name){
    if(!confirm(`Excluir "${name}" (#${id}) da fechadura?`))return;
    try{
      const r=await this.call("kt1000/delete_temp_password",{entry_id:this.data.entry_id,password_id:id});
      if(!r.ok)throw new Error(r.error||"Falha ao excluir");
      this.tempPasswords=null;this.tempPasswordError=null;this.render();
    }catch(e){alert(e.message||e);}
  }
  async loadLockUsers(){try{const r=await this.call("kt1000/lock_users",{entry_id:this.data.entry_id});if(!r.ok)throw new Error(r.error);const x=r.result||{};this.lockUsers=x.records||x.list||x.data||[];this.lockUsersError=null;}catch(e){this.lockUsers=[];this.lockUsersError=e.message||String(e);}this.render();}
  async remoteUnlock(){if(!confirm("Desbloquear a porta remotamente agora?\n\nEsta ação libera fisicamente a fechadura."))return;try{const r=await this.call("kt1000/remote_unlock",{entry_id:this.data.entry_id,confirmed:true});if(!r.ok)throw new Error(r.error||"Falha no desbloqueio");alert("Comando aceito pela Tuya. Verifique fisicamente a porta; isto não confirma sua abertura.");}catch(e){alert("Não foi possível desbloquear: "+(e.message||e));}}
  async renameOpmode(sn,current){const name=prompt("Novo nome da credencial:",current||"");if(name===null||!name.trim())return;try{const r=await this.call("kt1000/rename_opmode",{entry_id:this.data.entry_id,unlock_sn:sn,name:name.trim()});if(!r.ok)throw new Error(r.error);this.lockUsers=null;this.render();}catch(e){alert(e.message||e);}}
  async deleteUnlock(user,type,no,utype){if(!confirm(`Excluir definitivamente esta credencial ${type} #${no}?`))return;try{const r=await this.call("kt1000/delete_unlock_method",{entry_id:this.data.entry_id,user_id:String(user),unlock_type:type,unlock_no:Number(no),user_type:Number(utype||1)});if(!r.ok)throw new Error(r.error);this.lockUsers=null;this.render();}catch(e){alert(e.message||e);}}
  async enrollPassword(user,utype,replaceNo=null){const msg=replaceNo?`Trocar a senha fixa #${replaceNo}?\n\nA Tuya não permite enviar o novo PIN pela API desta fechadura Wi‑Fi. O sistema iniciará o cadastramento de uma nova senha para o MESMO usuário. Depois de concluir na fechadura, você poderá excluir a credencial antiga.`:`Iniciar o cadastramento de uma nova senha para este usuário?\n\nA nova senha será digitada na própria fechadura.`;if(!confirm(msg))return;try{const r=await this.call("kt1000/start_password_enrollment",{entry_id:this.data.entry_id,user_id:String(user),user_type:Number(utype||1)});if(!r.ok)throw new Error(r.error);alert("Modo de cadastramento solicitado. Conclua a nova senha no teclado da fechadura e depois clique em Atualizar.");}catch(e){alert(e.message||e);}}
  async enrollCredential(user,kind,replaceNo=null){const labels={password:"senha",fingerprint:"digital",card:"tag/cartão"};let msg=`Iniciar cadastro de ${labels[kind]} para este usuário?`;if(replaceNo)msg=`Trocar a senha #${replaceNo}?\n\nO cadastro de uma nova senha será iniciado para o mesmo usuário. Após concluir, exclua a credencial antiga.`;if(!confirm(msg))return;try{const r=await this.call("kt1000/start_credential_enrollment",{entry_id:this.data.entry_id,user_id:String(user),unlock_type:kind,user_type:2});if(!r.ok)throw new Error(r.error);alert(`Cadastro de ${labels[kind]} iniciado. Vá até a fechadura para concluir a captura/entrada. Depois clique em Atualizar.`);}catch(e){alert(e.message||e);}}
  newLockUserModal(){const dlg=this.shadowRoot.querySelector("#dlg"),m=this.shadowRoot.querySelector("#modal");m.innerHTML=`<h3>Novo usuário da fechadura</h3><input class="input" id="uname" placeholder="Nome" style="width:100%"><div style="margin-top:12px"><label><input type="checkbox" id="admin"> Administrador</label></div><div class="muted" style="margin-top:10px">O perfil administrador será solicitado à Tuya após criar o usuário. Alguns modelos de fechadura podem não aceitar alteração remota de perfil.</div><div class="modalrow"><button class="action" id="cancel">Cancelar</button><button class="action primary" id="save">Criar</button></div>`;dlg.showModal();m.querySelector("#cancel").onclick=()=>dlg.close();m.querySelector("#save").onclick=async()=>{const name=m.querySelector("#uname").value.trim();if(!name)return;try{const r=await this.call("kt1000/add_device_user",{entry_id:this.data.entry_id,nick_name:name,sex:1});if(!r.ok)throw new Error(r.error);const uid=(r.result&&r.result.user_id)||r.result;if(m.querySelector("#admin").checked&&uid){const rr=await this.call("kt1000/set_user_role",{entry_id:this.data.entry_id,user_id:String(uid),role:"admin"});if(!rr.ok)alert("Usuário criado, mas a KT-1000/Tuya não aceitou torná-lo administrador: "+rr.error);}dlg.close();this.lockUsers=null;this.render();}catch(e){alert(e.message||e);}}}
  async setUserRole(user,role){if(!confirm(role==="admin"?"Tornar este usuário administrador?":"Remover privilégios de administrador deste usuário?"))return;try{const r=await this.call("kt1000/set_user_role",{entry_id:this.data.entry_id,user_id:String(user),role});if(!r.ok)throw new Error(r.error);this.lockUsers=null;this.render();}catch(e){alert(e.message||e);}}
  async deleteLockUser(user,name){if(!confirm(`Excluir o usuário ${name} e suas associações da fechadura?`))return;try{const r=await this.call("kt1000/delete_device_user",{entry_id:this.data.entry_id,user_id:String(user)});if(!r.ok)throw new Error(r.error);this.lockUsers=null;this.render();}catch(e){alert(e.message||e);}}
  async editLockUser(user,current){const name=prompt("Nome do usuário:",current||"");if(name===null||!name.trim())return;try{const r=await this.call("kt1000/update_device_user",{entry_id:this.data.entry_id,user_id:String(user),nick_name:name.trim(),sex:1});if(!r.ok)throw new Error(r.error);this.lockUsers=null;this.render();}catch(e){alert(e.message||e);}}
  importModal(){
    const dlg=this.shadowRoot.querySelector("#dlg"),m=this.shadowRoot.querySelector("#modal");
    m.innerHTML=`<h3>Importar dados da integração</h3><p>Selecione uma cópia de .storage/kt1000.access e informe o entry_id da integração. Pessoas e histórico serão mesclados.</p><input type="file" id="importFile"><input class="input" id="importEntry" placeholder="entry_id"><p id="importMsg"></p><div class="modalrow"><button class="action" id="closeImport">Cancelar</button><button class="action primary" id="saveImport">Importar</button></div>`;
    dlg.showModal();m.querySelector("#closeImport").onclick=()=>dlg.close();m.querySelector("#saveImport").onclick=async()=>{try{const file=m.querySelector("#importFile").files[0];if(!file)throw new Error("Selecione o arquivo.");const data=JSON.parse(await file.text()),entry_id=m.querySelector("#importEntry").value.trim();const response=await fetch("./api/import",{method:"POST",headers:{"Content-Type":"application/json","X-KT1000-Request":"1"},body:JSON.stringify({data,entry_id})});const result=await response.json();if(!result.ok)throw new Error(result.error);dlg.close();await this.load();}catch(e){m.querySelector("#importMsg").textContent=e.message;}};
  }
  bind(){
    const lp=this.shadowRoot.querySelector("#localPeople"),cppl=this.shadowRoot.querySelector("#lockPeople");if(lp)lp.onclick=()=>{this.peopleMode="local";this.render();};if(cppl)cppl.onclick=()=>{this.peopleMode="lock";this.render();};
    const bp=this.shadowRoot.querySelector("#backPeople"),blp=this.shadowRoot.querySelector("#backLockPeople");if(bp)bp.onclick=()=>{this.selectedPerson=null;this.render();};if(blp)blp.onclick=()=>{this.selectedLockUser=null;this.render();};
    const ps=this.shadowRoot.querySelector("#peopleSearch");if(ps)ps.onchange=()=>{this.peopleSearch=ps.value;this.render();};
    this.shadowRoot.querySelectorAll(".openPerson").forEach(b=>b.onclick=()=>{this.selectedPerson=b.dataset.name;this.render();});
    this.shadowRoot.querySelectorAll(".openLockPerson").forEach(b=>b.onclick=()=>{this.selectedLockUser=b.dataset.user;this.render();});
    this.shadowRoot.querySelectorAll(".editPerson").forEach(b=>b.onclick=()=>this.personModal(b.dataset.name));
    const apc=this.shadowRoot.querySelector("#addPersonCredential");if(apc)apc.onclick=()=>this.addPersonCredentialModal(this.selectedPerson);
    this.shadowRoot.querySelectorAll(".transferPersonCredential").forEach(b=>b.onclick=()=>this.transferPersonCredentialModal(b.dataset.cred,b.dataset.person));
    this.shadowRoot.querySelectorAll(".removePersonCredential").forEach(b=>b.onclick=()=>this.removePersonCredential(b.dataset.cred,b.dataset.person));
    const of=this.shadowRoot.querySelector("#offlineFilter");if(of){of.value=this.offlineFilter;of.onchange=()=>{this.offlineFilter=of.value;this.offlinePage=1;this.render();};}
    const oi=this.shadowRoot.querySelector("#showInvalidOffline");if(oi)oi.onchange=()=>{this.showInvalidOffline=oi.checked;this.offlinePage=1;this.render();};
    const op=this.shadowRoot.querySelector("#prevOffline"),on=this.shadowRoot.querySelector("#nextOffline");if(op)op.onclick=()=>{this.offlinePage--;this.render();};if(on)on.onclick=()=>{this.offlinePage++;this.render();};
    this.shadowRoot.querySelectorAll(".offlineCode").forEach(b=>b.onclick=()=>this.revealOfflineCode(b.dataset.id));
    const refresh=this.shadowRoot.querySelector("#refreshConnection");if(refresh)refresh.onclick=async()=>{refresh.disabled=true;refresh.textContent="Consultando…";try{this.data=await this.call("kt1000/refresh");this.tempPasswords=null;this.tempPasswordError=null;this.lockUsers=null;this.lockUsersError=null;this.render();}catch(e){refresh.disabled=false;refresh.textContent="Atualizar conexão";alert(e.message||e);}};
    const imp=this.shadowRoot.querySelector("#importData");if(imp)imp.onclick=()=>this.importModal();
    const prev=this.shadowRoot.querySelector("#prevAccess"),next=this.shadowRoot.querySelector("#nextAccess");if(prev)prev.onclick=()=>{this.accessPage--;this.render()};if(next)next.onclick=()=>{this.accessPage++;this.render()};
    this.shadowRoot.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{this.tab=b.dataset.tab;this.render()});
    const f=this.shadowRoot.querySelector("#filter");if(f){f.value=this.filter;f.onchange=()=>{this.filter=f.value;this.accessPage=1;this.render()}}
    const q=this.shadowRoot.querySelector("#search");if(q)q.onchange=()=>{this.search=q.value;this.accessPage=1;this.render()};
    const np=this.shadowRoot.querySelector("#newPerson");if(np)np.onclick=()=>this.personModal();
    const rp=this.shadowRoot.querySelector("#refreshPasswords");if(rp)rp.onclick=()=>{if(this.passwordMode==="offline"){this.offlinePasswords=null;this.offlinePasswordError=null}else{this.tempPasswords=null;this.tempPasswordError=null}this.render()};
    const mo=this.shadowRoot.querySelector("#modeOnline");if(mo)mo.onclick=()=>{this.passwordMode="online";this.render()};const mf=this.shadowRoot.querySelector("#modeOffline");if(mf)mf.onclick=()=>{this.passwordMode="offline";this.render()};const sd=this.shadowRoot.querySelector("#showDeleted");if(sd)sd.onchange=()=>{this.showDeleted=sd.checked;this.render()};
    const cp=this.shadowRoot.querySelector("#createPassword");if(cp)cp.onclick=()=>this.createPasswordModal();
    const ru=this.shadowRoot.querySelector("#remoteUnlock");if(ru)ru.onclick=()=>this.remoteUnlock();
    const rlu=this.shadowRoot.querySelector("#refreshLockUsers");if(rlu)rlu.onclick=()=>{this.lockUsers=null;this.lockUsersError=null;this.render()};
    const nlu=this.shadowRoot.querySelector("#newLockUser");if(nlu)nlu.onclick=()=>this.newLockUserModal();
    this.shadowRoot.querySelectorAll(".addCredential").forEach(b=>b.onclick=()=>this.enrollCredential(b.dataset.user,b.dataset.kind));
    this.shadowRoot.querySelectorAll(".setRole").forEach(b=>b.onclick=()=>this.setUserRole(b.dataset.user,b.dataset.role));
    this.shadowRoot.querySelectorAll(".deleteLockUser").forEach(b=>b.onclick=()=>this.deleteLockUser(b.dataset.user,b.dataset.name));
    this.shadowRoot.querySelectorAll(".editLockUser").forEach(b=>b.onclick=()=>this.editLockUser(b.dataset.user,b.dataset.name));
    this.shadowRoot.querySelectorAll(".renameOpmode").forEach(b=>b.onclick=()=>this.renameOpmode(b.dataset.sn,b.dataset.name));
    this.shadowRoot.querySelectorAll(".deleteUnlock").forEach(b=>b.onclick=()=>this.deleteUnlock(b.dataset.user,b.dataset.type,b.dataset.no,b.dataset.utype));
    this.shadowRoot.querySelectorAll(".changeFixedPassword").forEach(b=>b.onclick=()=>this.enrollCredential(b.dataset.user,"password",b.dataset.sn));
    this.shadowRoot.querySelectorAll(".addFixedPassword").forEach(b=>b.onclick=()=>this.enrollPassword(b.dataset.user,b.dataset.utype));
    this.shadowRoot.querySelectorAll(".pwdDetail").forEach(b=>b.onclick=()=>this.passwordDetail(b.dataset.id));
    this.shadowRoot.querySelectorAll(".pwdDeleteRecord").forEach(b=>b.onclick=()=>this.deletePasswordRecord(b.dataset.id,b.dataset.name));
    this.shadowRoot.querySelectorAll(".pwdDelete").forEach(b=>b.onclick=()=>this.deletePassword(b.dataset.id,b.dataset.name));
    this.shadowRoot.querySelectorAll(".pwdFreeze").forEach(b=>b.onclick=()=>this.setPasswordFrozen(b.dataset.id,true));
    this.shadowRoot.querySelectorAll(".pwdUnfreeze").forEach(b=>b.onclick=()=>this.setPasswordFrozen(b.dataset.id,false));
    this.shadowRoot.querySelectorAll(".offlineClearOne").forEach(b=>b.onclick=()=>this.clearOfflineOne(b.dataset.id));
    this.shadowRoot.querySelectorAll(".assign").forEach(b=>b.onclick=()=>this.assignModal(b.dataset.cred));
    this.shadowRoot.querySelectorAll(".unassign").forEach(b=>b.onclick=async()=>{if(confirm("Desassociar esta credencial?")){await this.call("kt1000/unassign",{entry_id:this.data.entry_id,credential:b.dataset.cred});await this.load()}});
    this.shadowRoot.querySelectorAll(".deletePerson").forEach(b=>b.onclick=async()=>{if(confirm(`Excluir ${b.dataset.name}? As credenciais ficarão disponíveis para nova associação.`)){await this.call("kt1000/delete_person",{entry_id:this.data.entry_id,name:b.dataset.name});await this.load()}});
  }
  personModal(current=null){const dlg=this.shadowRoot.querySelector("#dlg"),m=this.shadowRoot.querySelector("#modal");m.innerHTML=`<h3>${current?"Editar pessoa":"Nova pessoa"}</h3><input class="input" id="pname" placeholder="Nome da pessoa" value="${this.escape(current||"")}" style="width:100%"><div class="modalrow"><button class="action" id="cancel">Cancelar</button><button class="action primary" id="save">Salvar</button></div><div class="unknown" id="personMessage"></div>`;dlg.showModal();m.querySelector("#cancel").onclick=()=>dlg.close();m.querySelector("#save").onclick=async()=>{const name=m.querySelector("#pname").value.trim();if(!name)return;try{await this.call("kt1000/save_person",{entry_id:this.data.entry_id,name,...(current?{old_name:current}:{})});this.selectedPerson=name;dlg.close();await this.load();}catch(e){m.querySelector("#personMessage").textContent=e.message||e;}}}
  assignModal(cred){const dlg=this.shadowRoot.querySelector("#dlg"),m=this.shadowRoot.querySelector("#modal");m.innerHTML=`<h3>Associar credencial</h3><div class="muted" style="margin-bottom:14px">${this.escape(cred)}</div><select id="person" style="width:100%">${this.data.people.map(p=>`<option>${this.escape(p.name)}</option>`).join("")}</select><div class="modalrow"><button class="action" id="cancel">Cancelar</button><button class="action primary" id="save">Associar</button></div>`;dlg.showModal();m.querySelector("#cancel").onclick=()=>dlg.close();m.querySelector("#save").onclick=async()=>{const person=m.querySelector("#person").value;if(person){await this.call("kt1000/assign",{entry_id:this.data.entry_id,person,credential:cred});dlg.close();await this.load()}}}
}
customElements.define("kt1000-panel",KT1000Panel);
